# Service expose

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  clusterIP: 10.101.78.56
  selector:
    app: rabbitmq
  ports:
  - name: default-1
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: default-2
    protocol: TCP
    port: 15672
    targetPort: 15672