apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-web
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: postgres-web-pvc
  hostPath:
    path: /data/postgres/web
#  storageClassName: slow
#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  nfs:
#    path: /tmp
#    server: 172.17.0.2