apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-1-hpa
  namespace: default
  labels:
    app: consumer-1-hpa
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90
