---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "consumer"
  namespace: "default"
  labels:
    app: "consumer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "consumer"
  template:
    metadata:
      labels:
        app: "consumer"
    spec:
      containers:
      - name: "consumer"
        image: "rpolnx/consumer"
        envFrom:
          - configMapRef:
              name: consumer-config
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 800m
          requests:
            cpu: 200m
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 2
          failureThreshold: 30
