
#Service
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  type: NodePort
  ports:
    - name: consumer
      protocol: TCP
      port: 8080
      targetPort: 8080