# Application
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "producer"
  namespace: "default"
  labels:
    app: "producer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "producer"
  template:
    metadata:
      labels:
        app: "producer"
    spec:
      containers:
      - name: "producer"
        image: "rpolnx/producer"
        envFrom:
          - configMapRef:
              name: producer-config
        ports:
        - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
